/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // ===== NewDB v2 (canonical) =====
        bg: 'var(--bg)',
        'bg-elev': 'var(--bg-elev)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        glass: 'var(--glass)',
        'glass-strong': 'var(--glass-strong)',

        text: 'var(--text)',
        'text-mute': 'var(--text-mute)',
        'text-dim': 'var(--text-dim)',
        'text-faint': 'var(--text-faint)',

        'accent-soft': 'var(--accent-soft)',
        'accent-2': 'var(--accent-2)',
        'accent-2-soft': 'var(--accent-2-soft)',
        'accent-3': 'var(--accent-3)',
        'data-4': 'var(--data-4)',
        'data-5': 'var(--data-5)',

        success: 'var(--success)',
        'success-soft': 'var(--success-soft)',
        warning: 'var(--warning)',
        'warning-soft': 'var(--warning-soft)',
        danger: 'var(--danger)',
        'danger-soft': 'var(--danger-soft)',
        'info-soft': 'var(--info-soft)',

        // ===== Legacy aliases (preservados, mapeiam para NewDB via :root) =====
        'bg-0': 'var(--bg-0)',
        'bg-1': 'var(--bg-1)',
        'bg-2': 'var(--bg-2)',
        'bg-3': 'var(--bg-3)',
        'bg-inset': 'var(--bg-inset)',

        'fg-1': 'var(--fg-1)',
        'fg-2': 'var(--fg-2)',
        'fg-3': 'var(--fg-3)',
        'fg-4': 'var(--fg-4)',

        accent: 'var(--accent)',
        'accent-ink': 'var(--accent-ink)',
        'accent-glow': 'var(--accent-glow)',

        pos: 'var(--pos)',
        neg: 'var(--neg)',
        warn: 'var(--warn)',
        info: 'var(--info)',

        'grain-soja': 'var(--grain-soja)',
        'grain-milho': 'var(--grain-milho)',
        'grain-trigo': 'var(--grain-trigo)',
        'grain-usd': 'var(--grain-usd)',

        'border-1': 'var(--border-1)',
        'border-2': 'var(--border-2)',

        // ===== VisionGlass tokens (namespace paralelo) =====
        'vg-bg': 'var(--vg-bg-surface)',
        'vg-bg-scrim': 'var(--vg-bg-scrim)',
        'vg-card': 'var(--vg-glass-card)',
        'vg-card-hover': 'var(--vg-glass-card-hover)',
        'vg-dock': 'var(--vg-glass-dock)',
        'vg-fg': 'var(--vg-fg-primary)',
        'vg-fg-2': 'var(--vg-fg-secondary)',
        'vg-fg-3': 'var(--vg-fg-tertiary)',
        'vg-fg-4': 'var(--vg-fg-quaternary)',
        'vg-accent': 'var(--vg-accent-primary)',
        'vg-accent-hover': 'var(--vg-accent-primary-hover)',
        'vg-accent-muted': 'var(--vg-accent-primary-muted)',
        'vg-destructive': 'var(--vg-accent-destructive)',
        'vg-success': 'var(--vg-accent-success)',
        'vg-warning': 'var(--vg-accent-warning)',
      },
      borderColor: {
        // NewDB
        DEFAULT: 'var(--border)',
        strong: 'var(--border-strong)',
        glass: 'var(--border-glass)',
        // Legacy
        'border-1': 'var(--border-1)',
        'border-2': 'var(--border-2)',
        'vg-border': 'var(--vg-glass-card-border)',
        'vg-border-strong': 'var(--vg-glass-card-border-strong)',
      },
      backdropBlur: {
        card: '20px',
        strong: '30px',
        'vg-card': '32px',
        'vg-dock': '40px',
      },
      borderRadius: {
        xs: 'var(--r-xs)',
        sm: 'var(--r-sm)',
        md: 'var(--r-md)',
        lg: 'var(--r-lg)',
        xl: 'var(--r-xl)',
        pill: 'var(--r-pill)',
        'vg-card': 'var(--vg-radius-card)',
        'vg-button': 'var(--vg-radius-button)',
        'vg-dock': 'var(--vg-radius-dock)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        7: 'var(--space-7)',
        8: 'var(--space-8)',
        9: 'var(--space-9)',
      },
      boxShadow: {
        'sh-1': 'var(--sh-1)',
        'sh-2': 'var(--sh-2)',
        'sh-3': 'var(--sh-3)',
        'sh-glow': 'var(--sh-glow)',
        card: 'var(--shadow-card)',
        pop: 'var(--shadow-pop)',
        glow: 'var(--shadow-glow)',
        'vg-card': 'var(--vg-shadow-card)',
        'vg-card-elevated': 'var(--vg-shadow-card-elevated)',
        'vg-dock': 'var(--vg-shadow-dock)',
        'vg-focus': 'var(--vg-shadow-focus)',
        'vg-glow': 'var(--vg-shadow-glow)',
      },
      fontFamily: {
        sans: ['var(--f-sans)', 'sans-serif'],
        mono: ['var(--f-mono)', 'monospace'],
        display: ['var(--f-display)', 'sans-serif'],
        serif: ['var(--f-serif)', 'serif'],
      },
      transitionTimingFunction: {
        'newdb': 'cubic-bezier(0.2, 0.7, 0.1, 1)',
      },
      transitionDuration: {
        '120': '120ms',
        '200': '200ms',
      },
      fontSize: {
        display: ['56px', { lineHeight: '1.05', letterSpacing: '-0.03em', fontWeight: '600' }],
        h1: ['40px', { lineHeight: '1.1', letterSpacing: '-0.025em', fontWeight: '600' }],
        h2: ['28px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h3: ['20px', { lineHeight: '1.3', letterSpacing: '-0.015em', fontWeight: '600' }],
        body: ['14px', { lineHeight: '1.5', letterSpacing: '0' }],
        small: ['12.5px', { lineHeight: '1.45', letterSpacing: '0.005em' }],
        micro: ['11px', { lineHeight: '1.4', letterSpacing: '0.04em' }],

        // ===== VisionGlass type scale =====
        'vg-display-xl': ['64px', { lineHeight: '1.04', letterSpacing: '-0.025em', fontWeight: '700' }],
        'vg-display-lg': ['48px', { lineHeight: '1.08', letterSpacing: '-0.02em', fontWeight: '700' }],
        'vg-h1':         ['32px', { lineHeight: '1.15', letterSpacing: '-0.015em', fontWeight: '700' }],
        'vg-h2':         ['24px', { lineHeight: '1.20', letterSpacing: '-0.01em', fontWeight: '600' }],
        'vg-h3':         ['20px', { lineHeight: '1.30', letterSpacing: '-0.005em', fontWeight: '600' }],
        'vg-body':       ['15px', { lineHeight: '1.47' }],
        'vg-label':      ['13px', { lineHeight: '1.30', fontWeight: '500' }],
        'vg-caption':    ['11px', { lineHeight: '1.36', letterSpacing: '0.01em', fontWeight: '500' }],
        'vg-metric':     ['28px', { lineHeight: '1.10', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
